#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/durgeshsingh/dev/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/durgeshsingh/Desktop/lib 2"
export "FLUTTER_TARGET=/Users/durgeshsingh/Desktop/lib 2/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/durgeshsingh/dev/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=2.4.1"
export "FLUTTER_BUILD_NUMBER=2.4.1"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
